"""
Answer & Verification Schemas
=============================

Typed contracts for the verification and generation pipeline:
    DraftAnswer — LLM-generated answer before verification
    ClaimVerificationResult — atomic assertion validation
    DomainRuleValidationResult — pluggable validator outcome
    VerificationResult — multi-metric verification output
    RoutingDecision — threshold routing to HIGH_CONFIDENCE / FALLBACK / BLOCKED
    VerifiedAnswer — final output combining answer, verification, and routing
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class RoutingRoute(str, Enum):
    """Output routing decision categories."""
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    FALLBACK_PARTIAL = "FALLBACK_PARTIAL"
    BLOCKED = "BLOCKED"


class IssueSeverity(str, Enum):
    """Categorization of verification failure severity."""
    REPAIRABLE = "REPAIRABLE"
    HIGH_RISK = "HIGH_RISK"
    BLOCKING = "BLOCKING"


class DraftAnswer(BaseModel):
    """
    Initial answer generated by the on-prem LLM from evidence only.
    """
    query_id: str = Field(..., description="FK → ConsolidatedEvidenceSet.query_id")
    text: str = Field(..., description="Generated answer text with inline citations")
    cited_chunks: list[str] = Field(default_factory=list, description="chunk_ids explicitly referenced")
    generation_model_id: str = Field(default="", description="Identifier of the LLM model used")
    generation_timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    model_config = {"extra": "forbid"}


class ClaimVerificationResult(BaseModel):
    """
    Atomic assertion validation.
    The answer is decomposed into claims, which are scored individually.
    """
    claim_id: str = Field(...)
    claim_text: str = Field(...)
    cited_chunk_ids: list[str] = Field(default_factory=list)
    
    entailment_score: float = Field(..., ge=0.0, le=1.0)
    contradiction_score: float = Field(..., ge=0.0, le=1.0)
    support_score: float = Field(..., ge=0.0, le=1.0)
    
    supported: bool = Field(...)
    blocking: bool = Field(default=False)
    issues: list[str] = Field(default_factory=list)

    model_config = {"extra": "forbid"}


class DomainRuleValidationResult(BaseModel):
    """Outcome of pluggable validators for specific domains."""
    domain_tag: str = Field(...)
    score: float = Field(..., ge=0.0, le=1.0)
    passed: bool = Field(...)
    blocking: bool = Field(default=False)
    issues: list[str] = Field(default_factory=list)
    reason_codes: list[str] = Field(default_factory=list)

    model_config = {"extra": "forbid"}


class VerificationResult(BaseModel):
    """
    Multi-metric verification output from the grounding loop.
    Contains both top-level metrics and granular claim evaluations.
    """
    relevance: float = Field(..., ge=0.0, le=1.0)
    intent_coverage: float = Field(..., ge=0.0, le=1.0)
    evidence_utilization: float = Field(..., ge=0.0, le=1.0)
    claim_similarity: float = Field(..., ge=0.0, le=1.0)
    consistency: float = Field(..., ge=0.0, le=1.0)
    citation_integrity: float = Field(..., ge=0.0, le=1.0)
    domain_rules: float = Field(..., ge=0.0, le=1.0)

    claims: list[ClaimVerificationResult] = Field(default_factory=list)
    domain_results: list[DomainRuleValidationResult] = Field(default_factory=list)

    issues: list[str] = Field(default_factory=list)
    issue_categories: list[str] = Field(default_factory=list)
    highest_severity: IssueSeverity | None = Field(default=None)

    iterations: int = Field(..., ge=1)

    model_config = {"extra": "forbid"}


class RoutingDecision(BaseModel):
    """
    Threshold routing decision determining how the answer is delivered.
    """
    route: RoutingRoute = Field(...)
    confidence: float = Field(..., ge=0.0, le=1.0)
    threshold_applied: float = Field(..., ge=0.0, le=1.0)
    explanation: str = Field(...)
    reason_codes: list[str] = Field(default_factory=list)

    model_config = {"extra": "forbid"}


class VerifiedAnswer(BaseModel):
    """
    Final output combining the answer, verification result, and routing decision.
    """
    query_id: str = Field(...)
    answer_text: str = Field(...)
    cited_chunks: list[str] = Field(default_factory=list)
    verification: VerificationResult
    routing: RoutingDecision
    evidence_snippets: list[dict[str, str]] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    model_config = {"extra": "forbid"}
